### PR TITLE
enable linting action

### PR DESCRIPTION
**Pull request by b00f**
This PR adds and enable check and linting action.

### CODE REVIEW

**Review by Ja7ad — APPROVED** [review]

**Comment by Ja7ad** [comment]
@b00f please check: https://github.com/pactus-project/pactus-website/actions/runs/11177384318/job/31072754179

**Comment by b00f** [comment]
@Ja7ad let's merge this PR, and we'll fix the broken links in a separate PR.

**Comment by Ja7ad** [comment]
> @Ja7ad let's merge this PR, and we'll fix the broken links in a separate PR.

Have conflicts

**Review by alidevjimmy — APPROVED** [review]

**Comment by b00f** [comment]
@alidevjimmy I think let's merge it now, and fix the rest in other PRs.

**Pull request merged**
